#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# restore wallpaper on startup
nitrogen --restore &

# start polybar
sh .config/bspwm/bin/launch_polybar.sh 

# start compositing
picom --config ~/.config/picom/picom.conf